SET XACT_ABORT ON;
BEGIN TRANSACTION;

/*
    多對多 Mapping Row 逐筆動態元件設定。
    MAPPING_ROW_ID 保存 MAPPING_PK_COLUMN 實際值的標準化字串。
*/
IF OBJECT_ID(N'dbo.FORM_MULTIPLE_MAPPING_COMPONENT_CONFIG', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.FORM_MULTIPLE_MAPPING_COMPONENT_CONFIG
    (
        ID uniqueidentifier NOT NULL,
        FORM_FIELD_MASTER_ID uniqueidentifier NOT NULL,
        MAPPING_ROW_ID nvarchar(450) NOT NULL,
        CONTROL_TYPE int NOT NULL,
        IS_USE_SQL bit NOT NULL
            CONSTRAINT DF_FORM_MM_COMPONENT_CONFIG_IS_USE_SQL DEFAULT (0),
        DROPDOWN_SQL nvarchar(max) NULL,
        CREATE_TIME datetime2(7) NOT NULL
            CONSTRAINT DF_FORM_MM_COMPONENT_CONFIG_CREATE_TIME DEFAULT (GETDATE()),
        EDIT_TIME datetime2(7) NULL,
        CREATE_USER nvarchar(128) NULL,
        EDIT_USER nvarchar(128) NULL,
        IS_DELETE bit NOT NULL
            CONSTRAINT DF_FORM_MM_COMPONENT_CONFIG_IS_DELETE DEFAULT (0),
        CONSTRAINT PK_FORM_MM_COMPONENT_CONFIG PRIMARY KEY (ID)
    );

    CREATE UNIQUE INDEX UX_FORM_MM_COMPONENT_CONFIG_ACTIVE_ROW
        ON dbo.FORM_MULTIPLE_MAPPING_COMPONENT_CONFIG
        (
            FORM_FIELD_MASTER_ID,
            MAPPING_ROW_ID
        )
        WHERE IS_DELETE = 0;
END;

IF OBJECT_ID(N'dbo.FORM_MULTIPLE_MAPPING_COMPONENT_OPTION', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.FORM_MULTIPLE_MAPPING_COMPONENT_OPTION
    (
        ID uniqueidentifier NOT NULL,
        COMPONENT_CONFIG_ID uniqueidentifier NOT NULL,
        OPTION_VALUE nvarchar(450) NOT NULL,
        OPTION_TEXT nvarchar(1000) NOT NULL,
        OPTION_ORDER int NOT NULL,
        CREATE_TIME datetime2(7) NOT NULL
            CONSTRAINT DF_FORM_MM_COMPONENT_OPTION_CREATE_TIME DEFAULT (GETDATE()),
        EDIT_TIME datetime2(7) NULL,
        CREATE_USER nvarchar(128) NULL,
        EDIT_USER nvarchar(128) NULL,
        IS_DELETE bit NOT NULL
            CONSTRAINT DF_FORM_MM_COMPONENT_OPTION_IS_DELETE DEFAULT (0),
        CONSTRAINT PK_FORM_MM_COMPONENT_OPTION PRIMARY KEY (ID),
        CONSTRAINT FK_FORM_MM_COMPONENT_OPTION_CONFIG
            FOREIGN KEY (COMPONENT_CONFIG_ID)
            REFERENCES dbo.FORM_MULTIPLE_MAPPING_COMPONENT_CONFIG (ID)
            ON DELETE CASCADE
    );

    CREATE UNIQUE INDEX UX_FORM_MM_COMPONENT_OPTION_ACTIVE_VALUE
        ON dbo.FORM_MULTIPLE_MAPPING_COMPONENT_OPTION
        (
            COMPONENT_CONFIG_ID,
            OPTION_VALUE
        )
        WHERE IS_DELETE = 0;

    CREATE INDEX IX_FORM_MM_COMPONENT_OPTION_ORDER
        ON dbo.FORM_MULTIPLE_MAPPING_COMPONENT_OPTION
        (
            COMPONENT_CONFIG_ID,
            OPTION_ORDER
        );
END;

COMMIT TRANSACTION;
