SET XACT_ABORT ON;
BEGIN TRANSACTION;

/*
    下拉選項新增選填的類型資訊。
    欄位允許 NULL，讓既有自訂選項與只有 ID／NAME 的 SQL 下拉選單維持相容。
*/
IF OBJECT_ID(N'dbo.FORM_FIELD_DROPDOWN_OPTIONS', N'U') IS NULL
BEGIN
    THROW 50000, N'找不到 dbo.FORM_FIELD_DROPDOWN_OPTIONS，無法新增 OPTION_TYPE。', 1;
END;

IF COL_LENGTH(N'dbo.FORM_FIELD_DROPDOWN_OPTIONS', N'OPTION_TYPE') IS NULL
BEGIN
    ALTER TABLE dbo.FORM_FIELD_DROPDOWN_OPTIONS
        ADD OPTION_TYPE nvarchar(255) NULL;
END;

COMMIT TRANSACTION;
